# Dependabot configuration file.
# See: https://docs.github.com/en/code-security/dependabot
version: 2

updates:
  # GitHub Actions dependency management.
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions-minor:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 15
    schedule:
      interval: weekly

  # NPM dependency management.
  - package-ecosystem: npm
    directory: /
    groups:
      npm-development-minor:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production-patch:
        dependency-type: production
        update-types:
          - patch
    open-pull-requests-limit: 15
    schedule:
      interval: weekly
