# ESLint Configuration File
# https://eslint.org/

env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - coverage
  - dist
  - megalinter-reports
  - node_modules

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  project:
    - tsconfig.eslint.json
  sourceType: module
  tsconfigRootDir: .

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: tsconfig.eslint.json

plugins:
  - '@typescript-eslint'
  - import
  - jest
  - prettier

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:prettier/recommended

rules:
  '@typescript-eslint/no-explicit-any': off
  import/no-namespace: off
  prettier/prettier: error
