# When a PR is merged, or when run manually, this workflow will build and
# package the GitHub Pages artifacts.
name: Continuous Delivery

on:
  push:
    branches:
      - main
  workflow_dispatch:

# prettier-ignore
env:
  NODE_CACHE: npm
  NODE_PUBLISH_URL: https://npm.pkg.github.com
  NODE_REGISTRY_URL: https://registry.npmjs.org
  NODE_VERSION_FILE: .node-version
  MANIFEST_PATH: package.json
  WORKING_DIRECTORY: ${{ github.workspace }}

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write
  security-events: write

jobs:
  cd:
    name: Release Node.js Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Tag
        id: tag
        uses: issue-ops/semver@v2
        with:
          manifest-path: package.json
          workspace: ${{ github.workspace }}
          ref: main

      - name: Create Release
        id: release
        uses: issue-ops/releaser@v2
        with:
          tag: v${{ steps.tag.outputs.version }}
