# This workflow runs a custom action, MegaLinter, which lints the entire
# codebase. It run's on every pull request (PR) targeting the `main` branch, and
# is a required check for any PR to be merged.
name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  packages: read
  pull-requests: write
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Lint Codebase
        id: lint
        uses: oxsecurity/megalinter/flavors/javascript@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
